invoker:
  appRequests:
    - app: AMAZON
      url: https://www.amazon.eg/s?k=mechanical+keyboard&crid=1H8R5QNS8VABR&language=en_AE&sprefix=%2Caps%2C131&ref=nb_sb_ss_recent_1_0_recent
      file: smt.html

scrapper:
  browser:
    visible: false
  outputDir: D:/_Temp/Shopping
  maxShippingPrice: 1000
  minDiscount: 20
  # EITHER, BOTH, SHIPPING, DISCOUNT
  searchRelation: DISCOUNT
#  -1 or limits
  minPrice: -1
  maxPrice: -1
