invoker:
  #  &language=en_AE
  appRequests:
    - app: AMAZON
      url: https://www.amazon.eg/s?rh=n%3A21840247031&fs=true&language=en&ref=lp_21840247031_sar
      file: snacks2.html

scrapper:
  browser:
    visible: true
  outputDir: D:/_Temp/Shopping/
  maxShippingPrice: 1000
  minDiscount: 20
  # EITHER, BOTH, SHIPPING, DISCOUNT
  searchRelation: DISCOUNT
  #  -1 or limits
  minPrice: -1
  maxPrice: -1
  #  save each n pages
  pageSaveFreq: 5
