invoker:
  #  &language=en_AE
  appRequests:
    - app: AMAZON
      url: https://www.amazon.co.jp/s?k=gaming+laptop&i=computers&rh=n%3A2127209051&dc&language=en&ds=v1%3AYL9Zf2E%2B0NH2X5Zo7tXHQBr4adUlTanZDXLsNfBtNq4&crid=2FNGLCLTDNJUI&qid=1700899194&sprefix=ga%2Caps%2C1537&ref=sr_ex_p_n_price_fma_0
      file: blackfriday-jp/laptop.html

scrapper:
  browser:
    visible: true
  outputDir: C:/Users/mh-sh/OneDrive/Documents/ShoppingScrapper/_/
  # outputDir: D:/_Temp/Shopping/
  maxShippingPrice: 0
  minDiscount: 10
  # EITHER, BOTH, SHIPPING, DISCOUNT
  searchRelation: DISCOUNT
  #  -1 or limits
  minPrice: -1
  maxPrice: -1
  #  save each n pages
  pageSaveFreq: 5
  #  runs long tasks in parallel with max size n
  batchSize: 30
